{{- if not .Values.existingSecret }}
{{- $fullName := include "pgadmin.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "pgadmin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  password: {{ default "SuperSecret" .Values.env.password | b64enc | quote }}
{{- if .Values.serverDefinitions.enabled }}
  servers.json: {{ include "pgadmin.serverDefinitions" . | b64enc | quote }}
{{- end }}
{{- end }}
